# -*- coding: utf-8 -*-
"""Penguin_Explorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4At6zu3S9JZm9GxSOeK4tU__Sesl90w
"""

import streamlit as st
import seaborn as sns
import plotly.express as px
import random
import pandas as pd

# Title
st.set_page_config(
    page_title="Penguin Explorer",
    layout="wide",
    page_icon="🐧"
)
st.title("Penguin Explorer - Devrielle Stokes")
st.markdown("<style>.stApp { background-color: #E6F7FF; }</style>", unsafe_allow_html=True)

# Load and prepare penguin data
penguins = sns.load_dataset("penguins").dropna()

# Add latitude & longitude for the map (simulated)
island_coords = {
    "Biscoe": (-63.8, -63.4),
    "Dream": (-64.7, -62.9),
    "Torgersen": (-64.8, -64.1)
}

penguins["latitude"] = penguins["island"].map(lambda x: island_coords[x][0] + random.uniform(-0.1, 0.1))
penguins["longitude"] = penguins["island"].map(lambda x: island_coords[x][1] + random.uniform(-0.1, 0.1))

# Map plot
fig_map = px.scatter_mapbox(
    penguins,
    lat="latitude",
    lon="longitude",
    color="species",
    color_discrete_map={"Adelie": "blue", "Chinstrap": "red", "Gentoo": "green"},
    title="Penguins by Species (map-based)",
    zoom=5
)
fig_map.update_layout(mapbox_style="open-street-map")
st.plotly_chart(fig_map)

# Violin plot
fig_violin = px.violin(
    penguins,
    x="species",
    y="body_mass_g",
    color="sex",
    box=True,
    points="all",
    title="Penguin Body Mass by Species and Sex"
)
st.plotly_chart(fig_violin)

with st.expander("Data Summary"):
    st.write(penguins.describe())

# Page Footer
st.markdown("---")
st.markdown("© 2025 • Built with ❤️ using Streamlit & Plotly @ VCU")